# Build only merge request and default branch
# and branches start with (develop).
# save time for quick demo pushes
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^develop/

.jazzy-setup:
  image: ros:jazzy-ros-core

.humble-setup:
  image: ros:humble-ros-core

include:
  - component: gitlab.com/ROSI-AP/rosi-ap_infrastructure/ci_templates/build-and-test@559983b81652d125ec2df7e5effd12085452ad62  # main
    inputs:
      job_name: jazzy
      ros_distro: "jazzy"
      setup_job_name: .jazzy-setup
      run_coverage: false

  - component: gitlab.com/ROSI-AP/rosi-ap_infrastructure/ci_templates/build-and-test@559983b81652d125ec2df7e5effd12085452ad62  # main
    inputs:
      job_name: humble
      ros_distro: "humble"
      setup_job_name: .humble-setup
      run_asan: false
      run_tsan: false
      coverage_exclude:
        - "*/test/*"
        - "*/examples/*"

# Build API Documentation
doxygen-docs:
  image: ubuntu:latest

  before_script:
    - apt-get -qq update
    - apt-get -y -qq install doxygen graphviz

  script:
    - (mkdir -p docs/doxygen/build && cd ./.doxygen && doxygen)

  artifacts:
    paths:
      - docs/doxygen/build/html/
    expire_in: 1 day

# Deploy docker jazzy image
docker-jazzy:
  image: docker:28.5.0
  services:
    - docker:28.5.0-dind
  before_script:
    # Login to registry
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
